datadir = "/var/lib/collectd/localhost"
dimensions = [300, 100]
span = "1h"
val = "value:AVERAGE"
color = "#FF0000"

[[graphs]]
title = "Memory Usage - 1 Hour"
lines = [
    { file = "memory/memory-used.rrd", name="Memory Used" },
    { file = "memory/memory-free.rrd", name="Memory Free", color="#00FF00" }
]
